export { default as HomeIcon } from './navigation/ic_home.svg';
export { default as RibbonIcon } from './navigation/ic_ribbon.svg';
export { default as CalendarIcon } from './navigation/ic_calendar.svg';
export { default as DebitCardIcon } from './navigation/ic_debit-card.svg';
export { default as DropboxIcon } from './navigation/ic_dropbox.svg';
export { default as FolderIcon } from './navigation/ic_folder.svg';
export { default as StudentIcon } from './navigation/ic_student.svg';
export { default as UserIcon } from './navigation/ic_user.svg';
export { default as SettingsIcon } from './navigation/ic_settings.svg';
export { default as ExitIcon } from './navigation/ic_exit.svg';
export {default as MegaphoneIcon } from './navigation/ic_announcement.svg';
export {default as ArrowIcon} from './navigation/ic_arrow.svg';
export {default as BellIcon} from './navigation/ic_bell.svg';
export {default as BurgerIcon} from './navigation/ic_burger.svg';
export {default as CloseIcon} from './navigation/ic_x.svg';
export {default as RightArrowIcon} from './navigation/ic_rightArrow.svg';
export {default as UploadIcon} from './navigation/ic_cloud-upload.svg';
export {default as DropArrowIcon} from './navigation/ic_arrow-drop.svg';
export {default as IdeaBulbIcon} from './navigation/ic_idea-bulb.svg';
export {default as PenIcon} from './buttons/ic_pen.svg';
export {default as TrashIcon} from './buttons/ic_trash.svg';
export {default as CheckIcon} from './status/ic_check.svg';
export {default as FilledRemoveIcon} from './status/ic_delete-close-remove-reject.svg';
export {default as PendingIcon} from './status/ic_pending.svg';